<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfUploadedFileTable extends Doctrine_Table
{
  public function findObsoletes($seconds = 3600)
  {
    return $this->createQuery('uf')
      ->where('uf.updated_at < ?', date('Y-m-d H:i:s', time() - $seconds))
      ->orderBy('uf.updated_at DESC')
      ->execute();
  }
}